apiVersion: v1
kind: Pod
metadata:
  labels:
    type: jenkins-agent
spec:
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
      - "/bin/sh"
      - "-c"
      - "sleep 99d"
    tty: true
    securityContext:
      runAsUser: 0
    resources:
      requests:
        memory: "256Mi"  
        cpu: "256m"      
      limits:
        memory: "512Mi"  
        cpu: "512m"
  restartPolicy: Never
